const userTypes = {
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
    SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
    SIGN_IN_ERROR: 'SIGN_IN_ERROR',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',

    

// to check
    SET_CURRENT_USER:  'SET_CURRENT_USER',
    SIGN_UP_ERROR: 'SIGN_UP_ERROR'
};

export default userTypes;