const trabajadoresTypes = {
    ADD_NEW_TRABAJADOR_START: 'ADD_NEW_TRABAJADOR_START',
    FETCH_TRABAJADORES_START: 'FETCH_TRABAJADORES_START',
    SET_TRABAJADORES: 'SET_TRABAJADORES',
    DELETE_TRABAJADOR_START: 'DELETE_TRABAJADOR_START',
    FETCH_TRABAJADOR_START: 'FETCH_TRABAJADOR_START',
    SET_TRABAJADOR: 'SET_TRABAJADOR',
};

export default trabajadoresTypes